# Generated by Django 5.1.4 on 2024-12-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_hand', models.JSONField(default=list)),
                ('dealer_hand', models.JSONField(default=list)),
                ('player_score', models.IntegerField(default=0)),
                ('dealer_score', models.IntegerField(default=0)),
                ('is_game_over', models.BooleanField(default=False)),
                ('winner', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
