# Generated by Django 5.1.4 on 2024-12-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='card_in_use',
            field=models.JSONField(default=list),
        ),
    ]
