# Generated by Django 5.1.4 on 2024-12-10 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_card_in_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='card_in_use',
        ),
    ]
